source /opt/rh/rh-ruby22/enable
export PATH=$PATH:/opt/rh/rh-ruby22/root/usr/bin:/opt/rh/rh-ruby22/root/usr/local/bin:/opt/rh/rh-ruby22/root/usr/bin:/opt/rh/rh-ruby22/root/usr/local/bin:/opt/rh/rh-ruby22/root/usr/bin:/opt/rh/rh-ruby22/root/usr/local/bin:~/bin
